# Generated by Django 5.1.2 on 2024-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_usermodels_delete_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('datetype', models.CharField(max_length=20)),
                ('predictValue', models.CharField(max_length=100)),
                ('modelId', models.CharField(max_length=30)),
            ],
        ),
    ]
